[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/36506730",
    "html_url": "https://github.com/electron/electron/pull/191#issuecomment-36506730",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/191",
    "id": 36506730,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2014-03-03T12:46:55Z",
    "updated_at": "2014-03-03T12:46:55Z",
    "body": "The mysterious problem is back, seems to be networking problem but I could not get more information, gaving up.\n"
  }
]