[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130074353",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130074353",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130074353,
    "user": {
      "login": "bengotow",
      "id": 1037212,
      "avatar_url": "https://avatars0.githubusercontent.com/u/1037212?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bengotow",
      "html_url": "https://github.com/bengotow",
      "followers_url": "https://api.github.com/users/bengotow/followers",
      "following_url": "https://api.github.com/users/bengotow/following{/other_user}",
      "gists_url": "https://api.github.com/users/bengotow/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bengotow/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bengotow/subscriptions",
      "organizations_url": "https://api.github.com/users/bengotow/orgs",
      "repos_url": "https://api.github.com/users/bengotow/repos",
      "events_url": "https://api.github.com/users/bengotow/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bengotow/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-11T21:00:58Z",
    "updated_at": "2015-08-11T21:00:58Z",
    "body": "Hi @s-a - you can bind node-inspector to the main process the same way you would a normal nodejs process: https://github.com/atom/electron/blob/master/docs/tutorial/debugging-main-process.md. If you pass `--debug-brk`, you can connect node-inspector and then break on the exception.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130080026",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130080026",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130080026,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-11T21:16:01Z",
    "updated_at": "2015-08-11T21:16:01Z",
    "body": "Ty for fast response. I require only scripts in webview. I wonder it crashes the main process. Does electron use bcrypt? Tried to check package json but there are only a few dev dependencies. Do you know where  I can find a dependency list of electron (prebuilt)? I suspect a version conflict... Will try your tip tomorrow.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130175864",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130175864",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130175864,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T05:33:48Z",
    "updated_at": "2015-08-12T05:33:48Z",
    "body": "@bengotow  This is not possible in this case because I require the Meteor run-time libs in my project. In this case it returns `--debug: unknown option.`. \n\nWould be new nice if main process errors could be written to \n- DevTools console or\n- terminal console or\n- file system or\n- OS event system log\n\nWhat do you think?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130307655",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130307655",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130307655,
    "user": {
      "login": "etiktin",
      "id": 4381579,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4381579?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etiktin",
      "html_url": "https://github.com/etiktin",
      "followers_url": "https://api.github.com/users/etiktin/followers",
      "following_url": "https://api.github.com/users/etiktin/following{/other_user}",
      "gists_url": "https://api.github.com/users/etiktin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etiktin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etiktin/subscriptions",
      "organizations_url": "https://api.github.com/users/etiktin/orgs",
      "repos_url": "https://api.github.com/users/etiktin/repos",
      "events_url": "https://api.github.com/users/etiktin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etiktin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T13:40:44Z",
    "updated_at": "2015-08-12T13:40:44Z",
    "body": "To to catch errors that occure in the main process you can use:\n\n``` javascript\nprocess.on('uncaughtException', function (error) {\n    // Handle the error\n}\n```\n\nWhen you set a listener for `uncaughtException`, Electron no longer outputs the error dialog from your first post. In the handler body, you can do what ever you want (output to console, show a custom error message etc.). You can also try to use `WebContents.executeJavaScript` and output an error message in the renderer side (if you use console.error, you should be able to see it in devtools). Keep in mind that when you get an `uncaughtException` the usual recommendation is to output an error and exit since the process is in unknown state, so trying to execute some code on the renderer side might fail.\n\nYou mentioned you're trying to load meteor app using Electron. Does meteor even works over io.js (last I checked it only worked with specific node.js versions)?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130322977",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130322977",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130322977,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T14:33:00Z",
    "updated_at": "2015-08-12T14:33:00Z",
    "body": "@etiktin \nHi, I already tried `uncaughtException` event handler in the main process `index.js`. Without success. \n\nYes I try to make it work. I recompiled all native modules against current Electron. No plan if its  possible but I already started a Meteor hello world app. Now I try the next step (example todo app) and I stumble on `bcrypt` which was also compiled successful. \n\nCannot figure out what tries to load bcrypt from where :smiley:   \n\nI overwrote require and put a break-point there to get informed over any require attempt. In this case the debugger does not stop. So I suspect the require comes from any internal compiled Electron code, but not sure about this and I have no more Ideas at this point. \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130331599",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130331599",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130331599,
    "user": {
      "login": "etiktin",
      "id": 4381579,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4381579?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etiktin",
      "html_url": "https://github.com/etiktin",
      "followers_url": "https://api.github.com/users/etiktin/followers",
      "following_url": "https://api.github.com/users/etiktin/following{/other_user}",
      "gists_url": "https://api.github.com/users/etiktin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etiktin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etiktin/subscriptions",
      "organizations_url": "https://api.github.com/users/etiktin/orgs",
      "repos_url": "https://api.github.com/users/etiktin/repos",
      "events_url": "https://api.github.com/users/etiktin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etiktin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T14:53:58Z",
    "updated_at": "2015-08-12T14:53:58Z",
    "body": "It's weird that `uncaughtException` didn't work for you. Maybe you can try the following:\nIn your main script, only register the `uncaughtException` handler and set a timer to require the rest of your code.\n\nRegarding meteor, I think it will be easier to first try and get meteor to work with the io.js version that electron uses. After you get it working with io.js, move the code to electron.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130335560",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130335560",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130335560,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T15:04:25Z",
    "updated_at": "2015-08-12T15:04:25Z",
    "body": "It is more weird that the exception is caused by a require statement from within webview code. So if I understand electron right this could not be a main process exception. Right?\nI agree this would be easier. I like the pain :)\nI do not require meteor code from main process.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130358320",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130358320",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130358320,
    "user": {
      "login": "etiktin",
      "id": 4381579,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4381579?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etiktin",
      "html_url": "https://github.com/etiktin",
      "followers_url": "https://api.github.com/users/etiktin/followers",
      "following_url": "https://api.github.com/users/etiktin/following{/other_user}",
      "gists_url": "https://api.github.com/users/etiktin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etiktin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etiktin/subscriptions",
      "organizations_url": "https://api.github.com/users/etiktin/orgs",
      "repos_url": "https://api.github.com/users/etiktin/repos",
      "events_url": "https://api.github.com/users/etiktin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etiktin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T16:12:27Z",
    "updated_at": "2015-08-12T16:12:27Z",
    "body": "I'm not sure. If you try to require something that doesn't exists in the renderer, do you get an `uncaughtException` in the main process?\nFor example:\n\n``` javascript\nvar remote = require('remote');\nvar foo = remote.require('a/b/c/d/foo');\n```\n\nIf you do get the exception, then it seems all node integration works through the main process. Maybe the issue you see with loading bcrypt is too low-level and `uncaughtException` can't catch it (you can see if that's the case by trying to load meteor in io.js, if `uncaughtException` won't catch it there, then it's not catchable).\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130363237",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130363237",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130363237,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-12T16:30:50Z",
    "updated_at": "2015-08-12T16:30:50Z",
    "body": "This will not throw exception in main process.\n\n![image](https://cloud.githubusercontent.com/assets/1270662/9229636/61a1607e-411e-11e5-9632-6b5f94e83860.png)\n\nI do not use `remote.require` I am working with `require` from renderer. And I overwrote `require` as follows : https://github.com/s-a/iron-node/blob/f419dc896d3f0cea91761ea9ff43fb9038ebaed6/app/require.js\nIt fixes the path for native modules respecting current v8 version. \n\nThe error occurs while it tries to load the wrong binary version because the code which caused the exception does not use my require version.\n\nMaybe this happens because bcrypt was required by another native module which does not know my `require` command?\n\nIn detail this is what i am trying here https://github.com/s-a/iron-node/blob/f419dc896d3f0cea91761ea9ff43fb9038ebaed6/docs/METEOR.md\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130824402",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130824402",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130824402,
    "user": {
      "login": "etiktin",
      "id": 4381579,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4381579?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etiktin",
      "html_url": "https://github.com/etiktin",
      "followers_url": "https://api.github.com/users/etiktin/followers",
      "following_url": "https://api.github.com/users/etiktin/following{/other_user}",
      "gists_url": "https://api.github.com/users/etiktin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etiktin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etiktin/subscriptions",
      "organizations_url": "https://api.github.com/users/etiktin/orgs",
      "repos_url": "https://api.github.com/users/etiktin/repos",
      "events_url": "https://api.github.com/users/etiktin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etiktin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-13T20:06:56Z",
    "updated_at": "2015-08-13T20:06:56Z",
    "body": "@s-a, why did you close this issue? Did you figure out how to catch the error? If not then I suggest you leave it open for some feedback from the project maintainers (it might help future answer seekers).\n\nDid you hear about [Electrometeor](https://github.com/sircharleswatson/Electrometeor)? They claim that they got meteor working on Electron. Maybe you can try to load bcrypt using their project and see what happens.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130827672",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130827672",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130827672,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-13T20:18:17Z",
    "updated_at": "2015-08-13T21:07:31Z",
    "body": "I do not want to create unnecessary noise. I wrote to the author of ElectroMeteor. Maybe he will answer. I updated to meteor 1.1.0.3 and the error is historie. Now it cannot find module `kexec` . I feel that success is near :smile: \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130829342",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130829342",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130829342,
    "user": {
      "login": "etiktin",
      "id": 4381579,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4381579?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etiktin",
      "html_url": "https://github.com/etiktin",
      "followers_url": "https://api.github.com/users/etiktin/followers",
      "following_url": "https://api.github.com/users/etiktin/following{/other_user}",
      "gists_url": "https://api.github.com/users/etiktin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etiktin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etiktin/subscriptions",
      "organizations_url": "https://api.github.com/users/etiktin/orgs",
      "repos_url": "https://api.github.com/users/etiktin/repos",
      "events_url": "https://api.github.com/users/etiktin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etiktin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-13T20:23:12Z",
    "updated_at": "2015-08-13T20:23:12Z",
    "body": "Good luck :+1: \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/130845353",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-130845353",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 130845353,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-13T21:07:56Z",
    "updated_at": "2015-08-13T21:07:56Z",
    "body": "After I upgraded the meteor project packages the error occurs again :crying_cat_face: \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134046179",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134046179",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134046179,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-08-24T05:39:09Z",
    "updated_at": "2015-08-24T05:39:09Z",
    "body": "Can you provide a demo? The dialog you see is actually created in `uncaughtException` handler.\n\nAnd for the error, I believe it is because you didn't follow [the right way](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) to install modules.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134050810",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134050810",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134050810,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-24T06:08:37Z",
    "updated_at": "2015-08-24T06:08:37Z",
    "body": "> I believe it is because you didn't follow the right way to install modules.\n\nYes this is what I am trying to do here. But I need more details about the exception to see what going on there.  \n\nI have registered the `uncaughtException` event like this. But the code will not reached in this exception case. \n\n``` javascript\nvar error = function(error) {\n        debugger;\n    console.error(error);\n    var msg = {\n        /*type : \"error\",\n        title : \"Uncaught Exception\",\n        buttons:[\"ok\", \"close\"],*/\n        width : 400\n    };\n\n    switch (typeof error) {\n        case \"object\":\n            msg.title = \"Uncaught Exception: \" + error.code;\n            msg.message = error.message;\n            break;\n        case \"string\":\n            msg.message = error;\n            break;\n    }\n    msg.detail = \"Please check the console log for more details.\";\n\n    ipc.send('electron-toaster-message', msg);\n}\n\nprocess.on('uncaughtException', error);\n```\n\n> Can you provide a demo?\n\nThis is not trivial. I tried this with `meteor create --example todos` example app. \n\nSteps to reproduce: \n- `npm install iron-node -g`\n- https://github.com/s-a/iron-node/blob/master/docs/METEOR.md\n  You nee to [setup meteor environment](https://github.com/s-a/iron-node/blob/master/docs/METEOR-DEBUG-BUILD.md#setup-metor-environment) before start the project.\n\nThe recompiling of native modules is non destructive. The build script will create a new folder for each binary handled by require function of my Electron app.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134051911",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134051911",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134051911,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-08-24T06:16:15Z",
    "updated_at": "2015-08-24T06:16:15Z",
    "body": "You need to setup `uncaughtException` handler in the main process since the exception happens there.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134061412",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134061412",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134061412,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-24T06:38:35Z",
    "updated_at": "2015-08-24T06:38:35Z",
    "body": "This is what @etiktin already mentioned. I ' ve tried that before.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134068167",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134068167",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134068167,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-08-24T07:06:44Z",
    "updated_at": "2015-08-24T07:06:44Z",
    "body": "Your `uncaughtException` handler is installed in the renderer process, that's why it doesn't work.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134069562",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134069562",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134069562,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-24T07:11:51Z",
    "updated_at": "2015-08-24T07:11:51Z",
    "body": "The code is not active in repository. I retried this again 30 minutes before.  My Handler should write a file to filesystem but it does not trigger. \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134070066",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134070066",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134070066,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-08-24T07:15:42Z",
    "updated_at": "2015-08-24T07:15:42Z",
    "body": "That's because you are listening to the `uncaughtException` in the wrong process. In your case you should do it in `index.js` instead of `app.js`.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134070314",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134070314",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134070314,
    "user": {
      "login": "s-a",
      "id": 1270662,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1270662?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s-a",
      "html_url": "https://github.com/s-a",
      "followers_url": "https://api.github.com/users/s-a/followers",
      "following_url": "https://api.github.com/users/s-a/following{/other_user}",
      "gists_url": "https://api.github.com/users/s-a/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s-a/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s-a/subscriptions",
      "organizations_url": "https://api.github.com/users/s-a/orgs",
      "repos_url": "https://api.github.com/users/s-a/repos",
      "events_url": "https://api.github.com/users/s-a/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s-a/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-24T07:17:49Z",
    "updated_at": "2015-08-24T07:17:49Z",
    "body": "That is what I have tried.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/134076276",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-134076276",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 134076276,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2015-08-24T07:45:41Z",
    "updated_at": "2015-08-24T07:45:41Z",
    "body": "Hmm from [your WIKI](https://github.com/s-a/iron-node/blob/master/docs/METEOR.md) you are using Electron as a replacement of upstream Node to run meteor, so the dialog you see doesn't come from your app, instead it comes from Meteor, if you want to catch that you have to modify Meteor's source code.\n\nAnd for the error you see, I think it is because the troubling module is placed under `packages` folder instead of `node_modules`, so `npm` and `node-gyp` won't be able to find it. \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/255869017",
    "html_url": "https://github.com/electron/electron/issues/2479#issuecomment-255869017",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2479",
    "id": 255869017,
    "user": {
      "login": "daniellmb",
      "id": 108018,
      "avatar_url": "https://avatars3.githubusercontent.com/u/108018?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/daniellmb",
      "html_url": "https://github.com/daniellmb",
      "followers_url": "https://api.github.com/users/daniellmb/followers",
      "following_url": "https://api.github.com/users/daniellmb/following{/other_user}",
      "gists_url": "https://api.github.com/users/daniellmb/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/daniellmb/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/daniellmb/subscriptions",
      "organizations_url": "https://api.github.com/users/daniellmb/orgs",
      "repos_url": "https://api.github.com/users/daniellmb/repos",
      "events_url": "https://api.github.com/users/daniellmb/events{/privacy}",
      "received_events_url": "https://api.github.com/users/daniellmb/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-10-24T21:18:12Z",
    "updated_at": "2016-10-24T21:25:05Z",
    "body": "Attaching to `process` wasn't enough for me. I also needed to hook into the error dialog to make sure I caught everything.\n\n``` js\n electron.dialog.showErrorBox = (title, content) => {\n  console.log(`${title}\\n${content}`);\n };\n```\n"
  }
]