[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/132729781",
    "html_url": "https://github.com/electron/electron/issues/2526#issuecomment-132729781",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2526",
    "id": 132729781,
    "user": {
      "login": "etiktin",
      "id": 4381579,
      "avatar_url": "https://avatars1.githubusercontent.com/u/4381579?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etiktin",
      "html_url": "https://github.com/etiktin",
      "followers_url": "https://api.github.com/users/etiktin/followers",
      "following_url": "https://api.github.com/users/etiktin/following{/other_user}",
      "gists_url": "https://api.github.com/users/etiktin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etiktin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etiktin/subscriptions",
      "organizations_url": "https://api.github.com/users/etiktin/orgs",
      "repos_url": "https://api.github.com/users/etiktin/repos",
      "events_url": "https://api.github.com/users/etiktin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etiktin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-19T18:16:59Z",
    "updated_at": "2015-08-19T18:16:59Z",
    "body": "This might be totally off, but did you check the permissions for the folder to make sure everything looks good? You can also try to run it with sudo and see if that works. If it does, then the issue is permissions.\n\nI may be wrong but from what I understand, Electron saves the `localStorage` to disk on exit only. So an issue with permissions or with an unclean exit (some uncaught exception), might explain why everything seems to work during execution but is not persisted to the next run.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/132851283",
    "html_url": "https://github.com/electron/electron/issues/2526#issuecomment-132851283",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2526",
    "id": 132851283,
    "user": {
      "login": "imskull",
      "id": 3264061,
      "avatar_url": "https://avatars1.githubusercontent.com/u/3264061?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/imskull",
      "html_url": "https://github.com/imskull",
      "followers_url": "https://api.github.com/users/imskull/followers",
      "following_url": "https://api.github.com/users/imskull/following{/other_user}",
      "gists_url": "https://api.github.com/users/imskull/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/imskull/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/imskull/subscriptions",
      "organizations_url": "https://api.github.com/users/imskull/orgs",
      "repos_url": "https://api.github.com/users/imskull/repos",
      "events_url": "https://api.github.com/users/imskull/events{/privacy}",
      "received_events_url": "https://api.github.com/users/imskull/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-20T02:07:18Z",
    "updated_at": "2015-08-20T02:07:18Z",
    "body": "Chrome 42 mobile has a several bug:  localStorage items are lost when the\napplication is forced to close\nhttps://code.google.com/p/chromium/issues/detail?id=479767 , I don't know\nif they are relative though.\n\nOn Thu, Aug 20, 2015 at 2:17 AM, Eran Tiktin notifications@github.com\nwrote:\n\n> This might be totally off, but did you check the permissions for the\n> folder to make sure everything looks good? You can also try to run it with\n> sudo and see if that works. If it does, then the issue is permissions.\n> \n> I may be wrong but from what I understand, Electron saves the localStorage\n> to disk on exit only. So an issue with permissions or with an unclean exit\n> (some uncaught exception), might explain why everything seems to work\n> during execution but is not persisted to the next run.\n> \n> â€”\n> Reply to this email directly or view it on GitHub\n> https://github.com/atom/electron/issues/2526#issuecomment-132729781.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/132897895",
    "html_url": "https://github.com/electron/electron/issues/2526#issuecomment-132897895",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2526",
    "id": 132897895,
    "user": {
      "login": "slothbag",
      "id": 811824,
      "avatar_url": "https://avatars1.githubusercontent.com/u/811824?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/slothbag",
      "html_url": "https://github.com/slothbag",
      "followers_url": "https://api.github.com/users/slothbag/followers",
      "following_url": "https://api.github.com/users/slothbag/following{/other_user}",
      "gists_url": "https://api.github.com/users/slothbag/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/slothbag/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/slothbag/subscriptions",
      "organizations_url": "https://api.github.com/users/slothbag/orgs",
      "repos_url": "https://api.github.com/users/slothbag/repos",
      "events_url": "https://api.github.com/users/slothbag/events{/privacy}",
      "received_events_url": "https://api.github.com/users/slothbag/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-20T05:28:52Z",
    "updated_at": "2015-08-20T05:28:52Z",
    "body": "Strange, none of the \"Resources\" information was showing in the DevTools pane, so I rebooted into Windows and confirmed that it was showing all the LocalStorage in the Resources tab.. rebooted back to Linux and now LocalStorage and all the Resources information is working.\n\nThanks for everyones input.. Closing this issue.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/132899399",
    "html_url": "https://github.com/electron/electron/issues/2526#issuecomment-132899399",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2526",
    "id": 132899399,
    "user": {
      "login": "slothbag",
      "id": 811824,
      "avatar_url": "https://avatars1.githubusercontent.com/u/811824?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/slothbag",
      "html_url": "https://github.com/slothbag",
      "followers_url": "https://api.github.com/users/slothbag/followers",
      "following_url": "https://api.github.com/users/slothbag/following{/other_user}",
      "gists_url": "https://api.github.com/users/slothbag/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/slothbag/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/slothbag/subscriptions",
      "organizations_url": "https://api.github.com/users/slothbag/orgs",
      "repos_url": "https://api.github.com/users/slothbag/repos",
      "events_url": "https://api.github.com/users/slothbag/events{/privacy}",
      "received_events_url": "https://api.github.com/users/slothbag/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-20T05:39:25Z",
    "updated_at": "2015-08-20T05:40:20Z",
    "body": "So looks like if you open an Electron app in linux, the first time the DevTools Resources pane works fine.  But if you close the app and re-run it again then the Resources pane is empty.\n\nI tried loging out and logging back in again but it still would not work.\n\nAfter rebooting I could see the Resources pane starts working again.. \n\nYesterday by LocalStorage variables were not working and now they are, so not sure how they are affected by this bug or if its a coincidence.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/132969150",
    "html_url": "https://github.com/electron/electron/issues/2526#issuecomment-132969150",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/2526",
    "id": 132969150,
    "user": {
      "login": "slothbag",
      "id": 811824,
      "avatar_url": "https://avatars1.githubusercontent.com/u/811824?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/slothbag",
      "html_url": "https://github.com/slothbag",
      "followers_url": "https://api.github.com/users/slothbag/followers",
      "following_url": "https://api.github.com/users/slothbag/following{/other_user}",
      "gists_url": "https://api.github.com/users/slothbag/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/slothbag/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/slothbag/subscriptions",
      "organizations_url": "https://api.github.com/users/slothbag/orgs",
      "repos_url": "https://api.github.com/users/slothbag/repos",
      "events_url": "https://api.github.com/users/slothbag/events{/privacy}",
      "received_events_url": "https://api.github.com/users/slothbag/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-20T10:40:18Z",
    "updated_at": "2015-08-20T10:40:18Z",
    "body": "Hard to pinpoint this. Closing issue for now.\n"
  }
]