[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/159413451",
    "html_url": "https://github.com/electron/electron/issues/3529#issuecomment-159413451",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3529",
    "id": 159413451,
    "user": {
      "login": "mark-hahn",
      "id": 811455,
      "avatar_url": "https://avatars1.githubusercontent.com/u/811455?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mark-hahn",
      "html_url": "https://github.com/mark-hahn",
      "followers_url": "https://api.github.com/users/mark-hahn/followers",
      "following_url": "https://api.github.com/users/mark-hahn/following{/other_user}",
      "gists_url": "https://api.github.com/users/mark-hahn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mark-hahn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mark-hahn/subscriptions",
      "organizations_url": "https://api.github.com/users/mark-hahn/orgs",
      "repos_url": "https://api.github.com/users/mark-hahn/repos",
      "events_url": "https://api.github.com/users/mark-hahn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mark-hahn/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-11-24T21:41:30Z",
    "updated_at": "2015-11-24T21:41:30Z",
    "body": "I did a test with the node version from atom 1.2.0 and node had no trouble writing to my fuse directory, so the problem must be in electron.\n\nHow to repeat this problem in just a few minutes...\n- download http://sourceforge.net/projects/fuse/files/fuse-2.X/2.9.4/\n- `cd fuse-2*`  you will be in this fuze install dir for the rest of these instructions\n- `./configure --prefix=/usr`\n- `make`\n- `mkdir fuze-dir` to make a dir to mount the fuze file system on\n- `sshfs localhost:/$home fuze-dir` to mount `$home` on `fuze-dir`\n- `ls -al fuze-dir` to see mount worked and permissions correct\n- `atom fuze-dir` with any atom after 1.1.0 and see permissions error\n- `umount fuze-dir` when done \n\nBTW, I found sshfs when creating these instructions but it looks like a very useful tool in general.  It can mount any remote directory as a local one.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/161408838",
    "html_url": "https://github.com/electron/electron/issues/3529#issuecomment-161408838",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3529",
    "id": 161408838,
    "user": {
      "login": "mark-hahn",
      "id": 811455,
      "avatar_url": "https://avatars1.githubusercontent.com/u/811455?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mark-hahn",
      "html_url": "https://github.com/mark-hahn",
      "followers_url": "https://api.github.com/users/mark-hahn/followers",
      "following_url": "https://api.github.com/users/mark-hahn/following{/other_user}",
      "gists_url": "https://api.github.com/users/mark-hahn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mark-hahn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mark-hahn/subscriptions",
      "organizations_url": "https://api.github.com/users/mark-hahn/orgs",
      "repos_url": "https://api.github.com/users/mark-hahn/repos",
      "events_url": "https://api.github.com/users/mark-hahn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mark-hahn/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-12-02T19:34:51Z",
    "updated_at": "2015-12-02T19:34:51Z",
    "body": "Must I assume this is low-priority and will not be fixed any time soon?  I need to know if I need to develop a new workflow. \n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/161531701",
    "html_url": "https://github.com/electron/electron/issues/3529#issuecomment-161531701",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3529",
    "id": 161531701,
    "user": {
      "login": "mark-hahn",
      "id": 811455,
      "avatar_url": "https://avatars1.githubusercontent.com/u/811455?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mark-hahn",
      "html_url": "https://github.com/mark-hahn",
      "followers_url": "https://api.github.com/users/mark-hahn/followers",
      "following_url": "https://api.github.com/users/mark-hahn/following{/other_user}",
      "gists_url": "https://api.github.com/users/mark-hahn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mark-hahn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mark-hahn/subscriptions",
      "organizations_url": "https://api.github.com/users/mark-hahn/orgs",
      "repos_url": "https://api.github.com/users/mark-hahn/repos",
      "events_url": "https://api.github.com/users/mark-hahn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mark-hahn/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-12-03T06:35:33Z",
    "updated_at": "2015-12-03T06:35:33Z",
    "body": "(Copy from atom/atom issue  https://github.com/atom/atom/issues/9555).\n\nI have found out that the parents of fuse directories had 600 permissions instead of the usual 755.  This means that any other user wouldn't be able to list the directory I was trying to open with Atom.  But I am always logged in as root and I always start atom with root.  So I think this is the wrong behavior.  Atom shouldn't behave like a different user.  Also it didn't have this problem until after 1.1.0.\n\nIn any case I have fixed my problem by setting all dirs to 755.  So I have a workaround.  If anyone wants I'll file another issue about this anomalous behavior but I'm closing this one. \n"
  }
]