[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/169204169",
    "html_url": "https://github.com/electron/electron/issues/3994#issuecomment-169204169",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3994",
    "id": 169204169,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-01-06T02:48:24Z",
    "updated_at": "2016-01-06T02:48:24Z",
    "body": "This is a client side error, caused by calling `disconnect` to a already disconnected process. You can debug into Nightmare to find out why it happened.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/170756150",
    "html_url": "https://github.com/electron/electron/issues/3994#issuecomment-170756150",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3994",
    "id": 170756150,
    "user": {
      "login": "serv",
      "id": 103456,
      "avatar_url": "https://avatars1.githubusercontent.com/u/103456?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/serv",
      "html_url": "https://github.com/serv",
      "followers_url": "https://api.github.com/users/serv/followers",
      "following_url": "https://api.github.com/users/serv/following{/other_user}",
      "gists_url": "https://api.github.com/users/serv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/serv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/serv/subscriptions",
      "organizations_url": "https://api.github.com/users/serv/orgs",
      "repos_url": "https://api.github.com/users/serv/repos",
      "events_url": "https://api.github.com/users/serv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/serv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-12T01:49:26Z",
    "updated_at": "2016-01-12T01:49:26Z",
    "body": "@felixcrive Hey I'm having the same issue on both Mac OSX and CentOS. Did you get a solve for the issue?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/170756468",
    "html_url": "https://github.com/electron/electron/issues/3994#issuecomment-170756468",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/3994",
    "id": 170756468,
    "user": {
      "login": "felixcrive",
      "id": 13838896,
      "avatar_url": "https://avatars2.githubusercontent.com/u/13838896?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/felixcrive",
      "html_url": "https://github.com/felixcrive",
      "followers_url": "https://api.github.com/users/felixcrive/followers",
      "following_url": "https://api.github.com/users/felixcrive/following{/other_user}",
      "gists_url": "https://api.github.com/users/felixcrive/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/felixcrive/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/felixcrive/subscriptions",
      "organizations_url": "https://api.github.com/users/felixcrive/orgs",
      "repos_url": "https://api.github.com/users/felixcrive/repos",
      "events_url": "https://api.github.com/users/felixcrive/events{/privacy}",
      "received_events_url": "https://api.github.com/users/felixcrive/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-12T01:51:41Z",
    "updated_at": "2016-01-12T01:51:41Z",
    "body": "@serv I haven't, apparently is a Nightmare bug, but if you find something please keep me posted. Thanks.\n"
  }
]