[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/205667738",
    "html_url": "https://github.com/electron/electron/issues/5031#issuecomment-205667738",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5031",
    "id": 205667738,
    "user": {
      "login": "Mr0grog",
      "id": 74178,
      "avatar_url": "https://avatars3.githubusercontent.com/u/74178?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Mr0grog",
      "html_url": "https://github.com/Mr0grog",
      "followers_url": "https://api.github.com/users/Mr0grog/followers",
      "following_url": "https://api.github.com/users/Mr0grog/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mr0grog/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mr0grog/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mr0grog/subscriptions",
      "organizations_url": "https://api.github.com/users/Mr0grog/orgs",
      "repos_url": "https://api.github.com/users/Mr0grog/repos",
      "events_url": "https://api.github.com/users/Mr0grog/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mr0grog/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-05T06:10:16Z",
    "updated_at": "2016-04-05T06:10:16Z",
    "body": "> Technically it didn't fail because of a user action per the Chromium net error docs: https://src.chromium.org/svn/trunk/src/net/base/net_error_list.h\n\nJust had an a-ha moment when I popped over here and read this. I'm _fairly_ sure in-page JS code counts as “user action” for Chromium in this context (non-user action here would be things like the server hanging up, some underlying subsystem in Chromium canceling the request, a proxy problem, etc. Anything happening _in the page,_ by contrast, is user action.), so it could very well be that some script on the page is manipulating an iframe or aborting an XHR, which would likely get you the result you're seeing.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/205731739",
    "html_url": "https://github.com/electron/electron/issues/5031#issuecomment-205731739",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5031",
    "id": 205731739,
    "user": {
      "login": "deepak1556",
      "id": 964386,
      "avatar_url": "https://avatars2.githubusercontent.com/u/964386?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/deepak1556",
      "html_url": "https://github.com/deepak1556",
      "followers_url": "https://api.github.com/users/deepak1556/followers",
      "following_url": "https://api.github.com/users/deepak1556/following{/other_user}",
      "gists_url": "https://api.github.com/users/deepak1556/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/deepak1556/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/deepak1556/subscriptions",
      "organizations_url": "https://api.github.com/users/deepak1556/orgs",
      "repos_url": "https://api.github.com/users/deepak1556/repos",
      "events_url": "https://api.github.com/users/deepak1556/events{/privacy}",
      "received_events_url": "https://api.github.com/users/deepak1556/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-05T09:40:19Z",
    "updated_at": "2016-04-05T09:40:19Z",
    "body": "@bmcminn its just as you have concluded, this happens for 204 responses. Its not request failed in this scenario, you can verify by capturing `log-net-log` and loading in `chrome://net-internals` instead blink just terminates further resource [load](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/loader/DocumentLoader.cpp&l=412&cl=GROK&gsn=WebURLError&rcl=1459826222) .  This termination actually occurs in the provisional stage of the request, but we have `did-fail-provisional-load` emit as `did-fail-load`, you can listen to `did-fail-provisional-load` to distinguish these failures (should be fixed @zcbenz ? ). To answer original feature request you can listen to `did-get-response-details`.\n\nFor bit more context on provisional load look [here](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/Fal1ZJnTgGQ/UDdxbrf_Rv4J)\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/206825384",
    "html_url": "https://github.com/electron/electron/issues/5031#issuecomment-206825384",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5031",
    "id": 206825384,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-04-07T11:33:12Z",
    "updated_at": "2016-04-07T11:33:12Z",
    "body": "Thanks for the answers, I'm closing this.\n"
  }
]