[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/206897388",
    "html_url": "https://github.com/electron/electron/issues/5051#issuecomment-206897388",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5051",
    "id": 206897388,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-04-07T13:21:02Z",
    "updated_at": "2016-04-07T13:21:02Z",
    "body": "It seems to be caused by the upgrade of Node. But you should not rely on this behavior any way, it totally depends on Node and does not work on certain platforms.\n\nI suggest hooking `process.stdout.write` and send the output to the main process to print. I'm closing this as won't fix.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/214715802",
    "html_url": "https://github.com/electron/electron/issues/5051#issuecomment-214715802",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5051",
    "id": 214715802,
    "user": {
      "login": "marton78",
      "id": 1110028,
      "avatar_url": "https://avatars3.githubusercontent.com/u/1110028?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/marton78",
      "html_url": "https://github.com/marton78",
      "followers_url": "https://api.github.com/users/marton78/followers",
      "following_url": "https://api.github.com/users/marton78/following{/other_user}",
      "gists_url": "https://api.github.com/users/marton78/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/marton78/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/marton78/subscriptions",
      "organizations_url": "https://api.github.com/users/marton78/orgs",
      "repos_url": "https://api.github.com/users/marton78/repos",
      "events_url": "https://api.github.com/users/marton78/events{/privacy}",
      "received_events_url": "https://api.github.com/users/marton78/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-04-26T11:52:51Z",
    "updated_at": "2016-04-26T11:52:51Z",
    "body": "This might be related to my problem so I won't open a new issue:\n\nWe develop an Electron app with a native node addon (written in C++, compiled with node-gyp). Since Electron v0.37, the native addon's output is not printed to stdout any more, which makes debugging it very difficult. Is there any way to restore the old behaviour?\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/214935258",
    "html_url": "https://github.com/electron/electron/issues/5051#issuecomment-214935258",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5051",
    "id": 214935258,
    "user": {
      "login": "zcbenz",
      "id": 639601,
      "avatar_url": "https://avatars3.githubusercontent.com/u/639601?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zcbenz",
      "html_url": "https://github.com/zcbenz",
      "followers_url": "https://api.github.com/users/zcbenz/followers",
      "following_url": "https://api.github.com/users/zcbenz/following{/other_user}",
      "gists_url": "https://api.github.com/users/zcbenz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zcbenz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zcbenz/subscriptions",
      "organizations_url": "https://api.github.com/users/zcbenz/orgs",
      "repos_url": "https://api.github.com/users/zcbenz/repos",
      "events_url": "https://api.github.com/users/zcbenz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zcbenz/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2016-04-27T01:06:46Z",
    "updated_at": "2016-04-27T01:06:46Z",
    "body": "@marton78 It should be some change in Node or libuv caused this, so there must be a way to revert that. I would be very happy to accept a PR to restore the old behavior, but we are not going to do it ourselves.\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/226961455",
    "html_url": "https://github.com/electron/electron/issues/5051#issuecomment-226961455",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5051",
    "id": 226961455,
    "user": {
      "login": "rahatarmanahmed",
      "id": 3174006,
      "avatar_url": "https://avatars0.githubusercontent.com/u/3174006?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rahatarmanahmed",
      "html_url": "https://github.com/rahatarmanahmed",
      "followers_url": "https://api.github.com/users/rahatarmanahmed/followers",
      "following_url": "https://api.github.com/users/rahatarmanahmed/following{/other_user}",
      "gists_url": "https://api.github.com/users/rahatarmanahmed/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rahatarmanahmed/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rahatarmanahmed/subscriptions",
      "organizations_url": "https://api.github.com/users/rahatarmanahmed/orgs",
      "repos_url": "https://api.github.com/users/rahatarmanahmed/repos",
      "events_url": "https://api.github.com/users/rahatarmanahmed/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rahatarmanahmed/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-18T19:46:55Z",
    "updated_at": "2016-06-18T19:51:54Z",
    "body": "@zcbenz This doesn't seem to be caused by a change in Node. Here's the `process.versions` of the two versions before and after the break:\n\n### Electron v0.37.2 process.versions\n\n``` json\n{\n  \"http_parser\": \"2.6.0\",\n  \"node\": \"5.1.1\",\n  \"v8\": \"4.9.385.28\",\n  \"uv\": \"1.7.5\",\n  \"zlib\": \"1.2.8\",\n  \"ares\": \"1.10.1-DEV\",\n  \"modules\": \"47\",\n  \"openssl\": \"1.0.2e\",\n  \"electron\": \"0.37.2\",\n  \"atom-shell\": \"0.37.2\",\n  \"chrome\": \"49.0.2623.75\"\n}\n```\n\n### Electron v0.37.3 process.versions\n\n``` json\n{\n  \"http_parser\": \"2.6.0\",\n  \"node\": \"5.1.1\",\n  \"v8\": \"4.9.385.28\",\n  \"uv\": \"1.7.5\",\n  \"zlib\": \"1.2.8\",\n  \"ares\": \"1.10.1-DEV\",\n  \"modules\": \"47\",\n  \"openssl\": \"1.0.2e\",\n  \"electron\": \"0.37.3\",\n  \"atom-shell\": \"0.37.3\",\n  \"chrome\": \"49.0.2623.75\"\n}\n```\n\nThe only thing that changed between these two versions was electron.\n\nThe bug is a bit of a minor inconvenience since you can work around it by sending ipc messages to the main process, but it'd be nice to have this fixed (particularly my problem is that I can't debug modules using the [`'debug'`](https://www.npmjs.com/package/debug) package, which works fine if i [shim process.stdout](https://github.com/squelch-irc/squelch/commit/e793dcf38c7119cec4e1531dab961abf511d377c))\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/226963079",
    "html_url": "https://github.com/electron/electron/issues/5051#issuecomment-226963079",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/5051",
    "id": 226963079,
    "user": {
      "login": "rahatarmanahmed",
      "id": 3174006,
      "avatar_url": "https://avatars0.githubusercontent.com/u/3174006?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rahatarmanahmed",
      "html_url": "https://github.com/rahatarmanahmed",
      "followers_url": "https://api.github.com/users/rahatarmanahmed/followers",
      "following_url": "https://api.github.com/users/rahatarmanahmed/following{/other_user}",
      "gists_url": "https://api.github.com/users/rahatarmanahmed/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rahatarmanahmed/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rahatarmanahmed/subscriptions",
      "organizations_url": "https://api.github.com/users/rahatarmanahmed/orgs",
      "repos_url": "https://api.github.com/users/rahatarmanahmed/repos",
      "events_url": "https://api.github.com/users/rahatarmanahmed/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rahatarmanahmed/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-18T20:24:41Z",
    "updated_at": "2016-06-19T07:05:56Z",
    "body": "~~Further investigation leads me to this commit: https://github.com/electron/node/commit/d6bccdb1a108ff99a5a7b572e88f7e40c58c1cd9. I guess it's failing to create the write stream and fallsback to a stream that writes to nothing. Seem to catch the error `Error: Unknown system error -25: Unknown system error -25, uv_pipe_open`, when trying to open a pipe with fd 1.~~\n\nLooks like i've only found out what zcbenz already knew. I think the issue is that between the two releases, libuv's `uv_guess_handle` gives two different results for the stdout fd. In 0.37.2 it guesses it's a TTY fd which seems to work. In 0.37.3 it guesses its a TCP fd, which leads it to try and open stdout as a socket and throw that error?\n\nWhat I don't get is how it returns two different results when `process.versions` says they're the same, and I don't see the node submodule being updated to a different commit when i compare the two versions: https://github.com/electron/electron/compare/v0.37.2...v0.37.3\n\nUPDATE: did a git bisect and it tells me the first commit where this bug happens is 0066833887aba619fd2f91e6462a9b001c54fa47\n"
  }
]