[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/242438384",
    "html_url": "https://github.com/electron/electron/issues/6974#issuecomment-242438384",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/6974",
    "id": 242438384,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-25T15:52:24Z",
    "updated_at": "2016-08-25T15:52:24Z",
    "body": "This has been discussed here #5344\n\nAs mentioned by @zcbenz in his reply to that issue.\n\n> For unhooking the callback automatically, it is basically impossible to implement since we can never how the callback is going to be used, for example a simple case like: win.on('event', => remoteCallback).\n> \n> And I don't think failing silently is an acceptable solution, it is just ignoring the problem.\n"
  }
]