[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281039175",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281039175",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281039175,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-20T10:14:38Z",
    "updated_at": "2017-02-20T10:14:38Z",
    "body": "@loreberti89 Sounds like at startup your computer hasn't connected to the internet yet, and your app simply failed to load a page.  Does that sound possible?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281040277",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281040277",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281040277,
    "user": {
      "login": "loreberti89",
      "id": 16079475,
      "avatar_url": "https://avatars2.githubusercontent.com/u/16079475?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/loreberti89",
      "html_url": "https://github.com/loreberti89",
      "followers_url": "https://api.github.com/users/loreberti89/followers",
      "following_url": "https://api.github.com/users/loreberti89/following{/other_user}",
      "gists_url": "https://api.github.com/users/loreberti89/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/loreberti89/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/loreberti89/subscriptions",
      "organizations_url": "https://api.github.com/users/loreberti89/orgs",
      "repos_url": "https://api.github.com/users/loreberti89/repos",
      "events_url": "https://api.github.com/users/loreberti89/events{/privacy}",
      "received_events_url": "https://api.github.com/users/loreberti89/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-20T10:19:24Z",
    "updated_at": "2017-02-20T10:23:49Z",
    "body": "@MarshallOfSound thankyou, I thought about it, but I tried to unplug the ethernet cable and restart the app, but it start and return error connection, but I see app html, if it was a connection problem, It should behave in the usual way if I unplug the cable"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281163298",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281163298",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281163298,
    "user": {
      "login": "groundwater",
      "id": 538488,
      "avatar_url": "https://avatars3.githubusercontent.com/u/538488?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/groundwater",
      "html_url": "https://github.com/groundwater",
      "followers_url": "https://api.github.com/users/groundwater/followers",
      "following_url": "https://api.github.com/users/groundwater/following{/other_user}",
      "gists_url": "https://api.github.com/users/groundwater/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/groundwater/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/groundwater/subscriptions",
      "organizations_url": "https://api.github.com/users/groundwater/orgs",
      "repos_url": "https://api.github.com/users/groundwater/repos",
      "events_url": "https://api.github.com/users/groundwater/events{/privacy}",
      "received_events_url": "https://api.github.com/users/groundwater/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-02-20T19:27:54Z",
    "updated_at": "2017-02-20T19:27:54Z",
    "body": "Hi @loreberti89, thanks for your report.\r\n\r\nUnfortunately it will be tough to track down the error if we cannot reproduce it. Are you able to share your application, and steps to reproduce the error?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281278634",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281278634",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281278634,
    "user": {
      "login": "loreberti89",
      "id": 16079475,
      "avatar_url": "https://avatars2.githubusercontent.com/u/16079475?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/loreberti89",
      "html_url": "https://github.com/loreberti89",
      "followers_url": "https://api.github.com/users/loreberti89/followers",
      "following_url": "https://api.github.com/users/loreberti89/following{/other_user}",
      "gists_url": "https://api.github.com/users/loreberti89/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/loreberti89/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/loreberti89/subscriptions",
      "organizations_url": "https://api.github.com/users/loreberti89/orgs",
      "repos_url": "https://api.github.com/users/loreberti89/repos",
      "events_url": "https://api.github.com/users/loreberti89/events{/privacy}",
      "received_events_url": "https://api.github.com/users/loreberti89/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-21T08:38:57Z",
    "updated_at": "2017-02-21T08:48:46Z",
    "body": "Hello @groundwater  thankyou, I will try to write a snippet for understand.\r\n\r\nIn **main.js**  I have  these require\r\n```\r\nconst electron = require('electron');\r\nconst {Menu, Tray} = require('electron');\r\nconst appExpress = require('express')();\r\nconst Redis = require('ioredis');\r\nconst path = require('path');\r\nconst url = require('url');\r\nconst http = require('http').Server(appExpress);\r\nconst https = require('https');\r\nconst io = require('socket.io')(http);\r\n```\r\n\r\nMaybe are too many? I don't know but the problem is when I try to do a async Call in main.js because if I comment the async call the app start correctly. My async call (in app.on('ready') obviously) is like this:\r\n\r\n```\r\nhttps.get(global.globalConfig.baseUrl + \"getListenPassword?key_access=\"+settings.get(\"key_access\"), function(res) {\r\n    res.on('data', function (body) {\r\n      global.globalConfig.redis =  JSON.parse(body).data;\r\n      const redis = new Redis({\r\n        port: 443,\r\n        host: 'mySite.it',\r\n        protocol: \"https\",\r\n        password: global.globalConfig.redis\r\n      })\r\n      redis.on('pmessage', function(subscribed, channel, message) {\r\n        message = JSON.parse(message);\r\n        notifier.notify({\r\n          'title': 'change state',\r\n          'message': 'The data with rif.'+message.data.data.id+' is changed',\r\n          sound: true,\r\n          icon: path.join(__dirname, '/images/icon.ico')\r\n        });\r\n        io.emit(channel + ':' + message.event, message.data);\r\n\r\n      });\r\n      redis.psubscribe(personal_event, function(err, count) {\r\n      });\r\n\r\n    });\r\n\r\n  }).on('error', function(e) {\r\n    console.log(\"Got error: \" + e.message);\r\n  });\r\n```\r\nAnd the problem isn't backend, because if it was, I would have the same problem when i try to disconnected user and reconnected user in windows.\r\n"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281294077",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281294077",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281294077,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-21T09:46:01Z",
    "updated_at": "2017-02-21T09:46:01Z",
    "body": "Hmm, I keep coming back to it being something to do with the network not being initialized during bootup.  Can you try commenting subsections out to isolate the exact call that causes the crash.  Or what might be easier is adding a script like this to your startup directory.\r\n\r\n```bash\r\nset ELECTRON_ENABLE_LOGGING=true\r\nset ELECTRON_ENABLE_STACK_DUMPING=true\r\npath\\to\\executable.exe\r\n```\r\n\r\nThat should launch a CMD prompt on logic and execute those commands allowing you to see any errors that may be being thrown either by your code or internal Electron things 👍 "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281313505",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281313505",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281313505,
    "user": {
      "login": "loreberti89",
      "id": 16079475,
      "avatar_url": "https://avatars2.githubusercontent.com/u/16079475?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/loreberti89",
      "html_url": "https://github.com/loreberti89",
      "followers_url": "https://api.github.com/users/loreberti89/followers",
      "following_url": "https://api.github.com/users/loreberti89/following{/other_user}",
      "gists_url": "https://api.github.com/users/loreberti89/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/loreberti89/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/loreberti89/subscriptions",
      "organizations_url": "https://api.github.com/users/loreberti89/orgs",
      "repos_url": "https://api.github.com/users/loreberti89/repos",
      "events_url": "https://api.github.com/users/loreberti89/events{/privacy}",
      "received_events_url": "https://api.github.com/users/loreberti89/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-21T11:10:44Z",
    "updated_at": "2017-02-21T11:10:44Z",
    "body": "@MarshallOfSound  I have resolved! \r\nIt's probably, as you say, a problem with connection initialize.\r\nSo I have used a IPC module for make a request in a moment when I am enough secure that the connection is established.\r\nThankyou for your help!"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/281528298",
    "html_url": "https://github.com/electron/electron/issues/8719#issuecomment-281528298",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/8719",
    "id": 281528298,
    "user": {
      "login": "groundwater",
      "id": 538488,
      "avatar_url": "https://avatars3.githubusercontent.com/u/538488?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/groundwater",
      "html_url": "https://github.com/groundwater",
      "followers_url": "https://api.github.com/users/groundwater/followers",
      "following_url": "https://api.github.com/users/groundwater/following{/other_user}",
      "gists_url": "https://api.github.com/users/groundwater/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/groundwater/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/groundwater/subscriptions",
      "organizations_url": "https://api.github.com/users/groundwater/orgs",
      "repos_url": "https://api.github.com/users/groundwater/repos",
      "events_url": "https://api.github.com/users/groundwater/events{/privacy}",
      "received_events_url": "https://api.github.com/users/groundwater/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-02-22T00:29:48Z",
    "updated_at": "2017-02-22T00:29:48Z",
    "body": "Sounds like this is solved. Going to close it."
  }
]