[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/296422716",
    "html_url": "https://github.com/electron/electron/issues/9263#issuecomment-296422716",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9263",
    "id": 296422716,
    "user": {
      "login": "patrickjuchli",
      "id": 397839,
      "avatar_url": "https://avatars1.githubusercontent.com/u/397839?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/patrickjuchli",
      "html_url": "https://github.com/patrickjuchli",
      "followers_url": "https://api.github.com/users/patrickjuchli/followers",
      "following_url": "https://api.github.com/users/patrickjuchli/following{/other_user}",
      "gists_url": "https://api.github.com/users/patrickjuchli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/patrickjuchli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/patrickjuchli/subscriptions",
      "organizations_url": "https://api.github.com/users/patrickjuchli/orgs",
      "repos_url": "https://api.github.com/users/patrickjuchli/repos",
      "events_url": "https://api.github.com/users/patrickjuchli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/patrickjuchli/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-04-23T06:24:16Z",
    "updated_at": "2017-04-23T06:25:37Z",
    "body": "I have some additional information:\r\n\r\nI tried to isolate the twitter-script in question by saving it locally and using a local HTML site. There was no crash here. The crash seems to be related to the origin `https://abs.twimg.com`. If I don't request the source of any scripts from this location it doesn't crash as well.\r\n\r\nThis looks very strange because I'm asking for the source *after* it has been parsed, the origin shouldn't be relevant at this point. What is the crash report above pointing at, how does this look from Electron's end? "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/297870495",
    "html_url": "https://github.com/electron/electron/issues/9263#issuecomment-297870495",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9263",
    "id": 297870495,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-04-27T23:54:14Z",
    "updated_at": "2017-04-28T00:25:59Z",
    "body": "> What is the crash report above pointing at, how does this look from Electron's end?\r\n\r\nSymbolicated the top line:\r\n\r\n`0   com.github.electron.framework \t0x000000010ec38334 0x10eb25000 + 1127220`\r\n\r\nto:\r\n\r\n`base::Value::IsType(base::Value::Type) const (in Electron Framework) (values.h:79)`\r\n\r\nSo looks like the message didn't parse as JSON and the pointer isn't checked to be null so it is crashing for that reason."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/297870930",
    "html_url": "https://github.com/electron/electron/issues/9263#issuecomment-297870930",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9263",
    "id": 297870930,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-04-27T23:57:08Z",
    "updated_at": "2017-04-27T23:57:08Z",
    "body": "Looks like this is the same crash as https://github.com/electron/electron/issues/9257 so I'm going to merge this issue into that one, please subscribe to that issue for updates."
  }
]