[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/300457979",
    "html_url": "https://github.com/electron/electron/issues/9416#issuecomment-300457979",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9416",
    "id": 300457979,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-10T11:48:16Z",
    "updated_at": "2017-05-10T11:48:16Z",
    "body": "@joaomoreno Can you test this out in raw node.js, I remember node having similar problems before with mounted file systems inside a VM"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/300813406",
    "html_url": "https://github.com/electron/electron/issues/9416#issuecomment-300813406",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9416",
    "id": 300813406,
    "user": {
      "login": "joaomoreno",
      "id": 22350,
      "avatar_url": "https://avatars0.githubusercontent.com/u/22350?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joaomoreno",
      "html_url": "https://github.com/joaomoreno",
      "followers_url": "https://api.github.com/users/joaomoreno/followers",
      "following_url": "https://api.github.com/users/joaomoreno/following{/other_user}",
      "gists_url": "https://api.github.com/users/joaomoreno/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joaomoreno/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joaomoreno/subscriptions",
      "organizations_url": "https://api.github.com/users/joaomoreno/orgs",
      "repos_url": "https://api.github.com/users/joaomoreno/repos",
      "events_url": "https://api.github.com/users/joaomoreno/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joaomoreno/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-11T14:50:08Z",
    "updated_at": "2017-05-11T14:50:08Z",
    "body": "This does **not** repro in Node. I simply get a `EISDIR` error in vanilla Node 7.4.0."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/301538060",
    "html_url": "https://github.com/electron/electron/issues/9416#issuecomment-301538060",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9416",
    "id": 301538060,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-05-15T17:03:32Z",
    "updated_at": "2017-05-15T17:03:32Z",
    "body": "@joaomoreno are you able to provide the stack trace from the crash?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/301710435",
    "html_url": "https://github.com/electron/electron/issues/9416#issuecomment-301710435",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9416",
    "id": 301710435,
    "user": {
      "login": "joaomoreno",
      "id": 22350,
      "avatar_url": "https://avatars0.githubusercontent.com/u/22350?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joaomoreno",
      "html_url": "https://github.com/joaomoreno",
      "followers_url": "https://api.github.com/users/joaomoreno/followers",
      "following_url": "https://api.github.com/users/joaomoreno/following{/other_user}",
      "gists_url": "https://api.github.com/users/joaomoreno/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joaomoreno/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joaomoreno/subscriptions",
      "organizations_url": "https://api.github.com/users/joaomoreno/orgs",
      "repos_url": "https://api.github.com/users/joaomoreno/repos",
      "events_url": "https://api.github.com/users/joaomoreno/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joaomoreno/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-16T08:20:05Z",
    "updated_at": "2017-05-16T08:20:28Z",
    "body": "@kevinsawicki I'm finding it very tough to get a crash report out of it. No crash dumps appear in `TEMP`. When I run `process.crash()` I do get a crash dump in there, though.\r\n\r\nI've configured the app to talk to a dummy crash report service.\r\n\r\nHere's what `output_log.txt` shows for my crash:\r\n\r\n```\r\n[1272:4052:0516/011647.856:VERBOSE1:crash_service_main.cc(78)] Session start. cmdline is [--reporter-url=https://your-domain.com/url-to-submit --application-name=YourName \"--crashes-directory=C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\" --v=1]\r\n[1272:4052:0516/011647.859:VERBOSE1:crash_service.cc(142)] window handle is 001804AA\r\n[1272:4052:0516/011647.859:VERBOSE1:crash_service.cc(284)] pipe name is \\\\.\\pipe\\YourName Crash Service\r\ndumps at C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\r\n[1272:4052:0516/011647.859:VERBOSE1:crash_service.cc(288)] checkpoint is C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\\crash_checkpoint.txt\r\nserver is https://your-domain.com/url-to-submit\r\nmaximum 128 reports/day\r\nreporter is electron-crash-service\r\n[1272:4052:0516/011647.859:VERBOSE1:crash_service_main.cc(94)] Ready to process crash requests\r\n[1272:3904:0516/011647.865:VERBOSE1:crash_service.cc(317)] client start. pid = 2532\r\n[1272:4084:0516/011654.365:VERBOSE1:crash_service.cc(325)] client end. pid = 2532\r\n[1272:4084:0516/011655.365:VERBOSE1:crash_service.cc(346)] zero clients. exiting\r\n[1272:4052:0516/011655.366:VERBOSE1:crash_service.cc(486)] session ending..\r\n[1272:4052:0516/011655.417:VERBOSE1:crash_service.cc(491)] clients connected :1\r\nclients terminated :1\r\ndumps serviced :0\r\ndumps reported :0\r\n[1272:4052:0516/011655.417:VERBOSE1:crash_service_main.cc(99)] Session end. return code is 0\r\n```\r\n\r\nHere's what it shows for `process.crash()`:\r\n\r\n```\r\n[772:4092:0516/011617.487:VERBOSE1:crash_service_main.cc(78)] Session start. cmdline is [--reporter-url=https://your-domain.com/url-to-submit --application-name=YourName \"--crashes-directory=C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\" --v=1]\r\n[772:4092:0516/011617.490:VERBOSE1:crash_service.cc(142)] window handle is 0011044C\r\n[772:4092:0516/011617.490:VERBOSE1:crash_service.cc(284)] pipe name is \\\\.\\pipe\\YourName Crash Service\r\ndumps at C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\r\n[772:4092:0516/011617.490:VERBOSE1:crash_service.cc(288)] checkpoint is C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\\crash_checkpoint.txt\r\nserver is https://your-domain.com/url-to-submit\r\nmaximum 128 reports/day\r\nreporter is electron-crash-service\r\n[772:4092:0516/011617.490:VERBOSE1:crash_service_main.cc(94)] Ready to process crash requests\r\n[772:936:0516/011617.495:VERBOSE1:crash_service.cc(317)] client start. pid = 2228\r\n[772:936:0516/011618.592:VERBOSE1:crash_service.cc(388)] dump for pid = 2228 is C:\\Users\\IEUser\\AppData\\Local\\Temp\\YourName Crashes\\2500b72d-dbc3-4942-acf3-e19c6968208d.dmp\r\n[772:2060:0516/011618.634:VERBOSE1:crash_service.cc(436)] trying to send report for pid = 2228\r\n[772:4012:0516/011618.653:VERBOSE1:crash_service.cc(325)] client end. pid = 2228\r\n[772:2060:0516/011624.368:VERBOSE1:crash_service.cc(468)] dump for pid =2228 crash2 id =<network issue>\r\n[772:4012:0516/011624.370:VERBOSE1:crash_service.cc(346)] zero clients. exiting\r\n[772:4092:0516/011624.370:VERBOSE1:crash_service.cc(486)] session ending..\r\n[772:4092:0516/011624.421:VERBOSE1:crash_service.cc(491)] clients connected :1\r\nclients terminated :1\r\ndumps serviced :0\r\ndumps reported :0\r\n[772:4092:0516/011624.421:VERBOSE1:crash_service_main.cc(99)] Session end. return code is 0\r\n```"
  }
]