[
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/304681272",
    "html_url": "https://github.com/electron/electron/issues/9614#issuecomment-304681272",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9614",
    "id": 304681272,
    "user": {
      "login": "MarshallOfSound",
      "id": 6634592,
      "avatar_url": "https://avatars0.githubusercontent.com/u/6634592?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarshallOfSound",
      "html_url": "https://github.com/MarshallOfSound",
      "followers_url": "https://api.github.com/users/MarshallOfSound/followers",
      "following_url": "https://api.github.com/users/MarshallOfSound/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarshallOfSound/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarshallOfSound/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarshallOfSound/subscriptions",
      "organizations_url": "https://api.github.com/users/MarshallOfSound/orgs",
      "repos_url": "https://api.github.com/users/MarshallOfSound/repos",
      "events_url": "https://api.github.com/users/MarshallOfSound/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarshallOfSound/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-29T14:57:25Z",
    "updated_at": "2017-05-29T14:57:25Z",
    "body": "> LINK : fatal error LNK1181: cannot open input file 'C:\\Users\\shiftkey\\src\\electron\\dist\\node-v1.7.2\\Release\\iojs.lib\r\n\r\nI've had that error recently, I had to roll back my local node version to v6 and then it started working.  Maybe try that out?"
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/304716176",
    "html_url": "https://github.com/electron/electron/issues/9614#issuecomment-304716176",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9614",
    "id": 304716176,
    "user": {
      "login": "shiftkey",
      "id": 359239,
      "avatar_url": "https://avatars1.githubusercontent.com/u/359239?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shiftkey",
      "html_url": "https://github.com/shiftkey",
      "followers_url": "https://api.github.com/users/shiftkey/followers",
      "following_url": "https://api.github.com/users/shiftkey/following{/other_user}",
      "gists_url": "https://api.github.com/users/shiftkey/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shiftkey/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shiftkey/subscriptions",
      "organizations_url": "https://api.github.com/users/shiftkey/orgs",
      "repos_url": "https://api.github.com/users/shiftkey/repos",
      "events_url": "https://api.github.com/users/shiftkey/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shiftkey/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-05-29T19:02:34Z",
    "updated_at": "2017-05-29T19:02:34Z",
    "body": "@MarshallOfSound I tried that with `v6.10.3` but the same errors occur."
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/304959499",
    "html_url": "https://github.com/electron/electron/issues/9614#issuecomment-304959499",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9614",
    "id": 304959499,
    "user": {
      "login": "kevinsawicki",
      "id": 671378,
      "avatar_url": "https://avatars0.githubusercontent.com/u/671378?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevinsawicki",
      "html_url": "https://github.com/kevinsawicki",
      "followers_url": "https://api.github.com/users/kevinsawicki/followers",
      "following_url": "https://api.github.com/users/kevinsawicki/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevinsawicki/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevinsawicki/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevinsawicki/subscriptions",
      "organizations_url": "https://api.github.com/users/kevinsawicki/orgs",
      "repos_url": "https://api.github.com/users/kevinsawicki/repos",
      "events_url": "https://api.github.com/users/kevinsawicki/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevinsawicki/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-05-30T18:01:39Z",
    "updated_at": "2017-05-30T18:01:39Z",
    "body": "@shiftkey can you try latest master? I think this may have been addressed by #9589 "
  },
  {
    "url": "https://api.github.com/repos/electron/electron/issues/comments/304970321",
    "html_url": "https://github.com/electron/electron/issues/9614#issuecomment-304970321",
    "issue_url": "https://api.github.com/repos/electron/electron/issues/9614",
    "id": 304970321,
    "user": {
      "login": "shiftkey",
      "id": 359239,
      "avatar_url": "https://avatars1.githubusercontent.com/u/359239?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shiftkey",
      "html_url": "https://github.com/shiftkey",
      "followers_url": "https://api.github.com/users/shiftkey/followers",
      "following_url": "https://api.github.com/users/shiftkey/following{/other_user}",
      "gists_url": "https://api.github.com/users/shiftkey/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shiftkey/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shiftkey/subscriptions",
      "organizations_url": "https://api.github.com/users/shiftkey/orgs",
      "repos_url": "https://api.github.com/users/shiftkey/repos",
      "events_url": "https://api.github.com/users/shiftkey/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shiftkey/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2017-05-30T18:41:41Z",
    "updated_at": "2017-05-30T18:41:41Z",
    "body": "@kevinsawicki aside from the warning messages in `update.py` this seems to be fine:\r\n\r\n```\r\n...\r\nC:\\Python27\\python.exe C:\\Users\\shiftkey\\src\\electron\\script\\update.py --msvs\r\nDownload directxsdk-x64     1806291  [100.0%]\r\nWarning: Missing input files:\r\nvendor\\node\\src\\tracing\\trace_event.hsrc\\tree.h\r\nWarning: Missing input files:\r\nvendor\\node\\src\\tracing\\trace_event.hsrc\\tree.h\r\n```\r\n\r\nAnd I have a working `electron.sln` file at the root of the repository now, so I'm gonna close this out. Thanks for the update!"
  }
]